# Generated by Django 3.0 on 2020-06-29 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='category',
            field=models.CharField(default='Select category', max_length=255),
        ),
        migrations.AddField(
            model_name='tasks',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='link',
            field=models.URLField(blank=True, max_length=2083),
        ),
    ]
