# Generated by Django 3.0 on 2020-06-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200629_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_type',
            name='category_type',
        ),
        migrations.AddField(
            model_name='category_type',
            name='Category',
            field=models.CharField(default='Add a new category', max_length=255),
        ),
    ]
