# Generated by Django 3.0 on 2020-06-30 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_auto_20200629_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='duration',
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category_type',
            name='Category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
