# Generated by Django 3.0 on 2020-06-30 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200630_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
